### ISSUE TITLE
[1] Benchmark ETL time

### ISSUE THREAD

**Issue by debnil** [stellar/stellar-etl-airflow#28]
**What**
We should benchmark the time to run the ETL from genesis to current ledger, in line with our conversation with Google PDP.

**Why**
This will give ballpark figures that help them ensure quality of deployment.

**Comment by Isaiah-Turner** [comment]
<img width="1792" alt="HistoryArchiveTiming" src="https://user-images.githubusercontent.com/42742035/93527180-7b2eb500-f906-11ea-8985-b776f199ae87.png">
The above graph is the task timings for the history archives. I would say it takes ~13 seconds to complete a history archive export. Most of the time is in sending data to BigQuery. Getting ledger ranges from time ranges also is fairly time consuming. Exporting data using the ETL does not take much time, and loading data into GCS is very fast. There are occasional spikes in the time of these tasks. I'm not sure why this happens. If I had to guess, its because the Airflow settings are too difficult on my Mac. I'm running up to 16 DAGs in parallel, and my Mac is probably struggling on the 15-16th DAG, making it take longer than normal.
<br/><br/>
The DAG that processes the unbounded core takes less than 10 seconds to finish. I wasn't able to get a nice graph for it, but since batches are exported every 5 minutes from core, the timing should be fine.

**Comment by debnil** [comment]
Nice, thanks for the graph!! So to be clear, this is per-checkpoint?

**Comment by Isaiah-Turner** [comment]
Yes, it is. Also, the relevant Airflow setting I'm using are: 
- dag_concurrency = 16 (The number of task instances allowed to run concurrently by the scheduler)
- parallelism = 32 (the max number of task instances that should run simultaneously)

**Comment by Isaiah-Turner** [comment]
The network was created on 09-30-2015. It has been running for 1814 days, or 2612160 minutes. This means there are roughly 522432 checkpoints that we will have to export, for a total runtime of 6791616 seconds or ~79 days. 
Of course, we can run DAGs in parallel. On my Mac, which has been running 16 DAGs at once, we would need a little less than 5 days. More powerful machines will be even faster.
